theme: jekyll-theme-hacker

plugins:
    # https://github.com/gjtorikian/jekyll-last-modified-at
    - jekyll-last-modified-at

# Optional. The default date format, used if none is specified in the tag.
last-modified-at:
    date-format: '%d-%b-%y'